### ISSUE TITLE
gun0912.tedbottompicker.TedBottomPicker.checkMultiMode

### ISSUE THREAD

**Issue by emad3oon** [ParkSangGwon/TedBottomPicker#104]
Fatal Exception: java.lang.RuntimeException
Failure delivering result ResultInfo{who=null, request=59831, result=-1, data=null} to activity {interactive.ksi.com.alsoug/com.gun0912.tedonactivityresult.ProxyActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference

**Comment by ParkSangGwon** [comment]
Can you show sample code?

**Comment by PR0GGRAM3D2WIN** [comment]
# Date: 2019-06-14T12:42:00Z
# OS Version: 8.1.0
# Device: SM-G610F
# RAM Free: 17%
# Disk Free: 11.8%
# TedBottomPickerLibraryVersion: 2.0.1

#0. Crashed: main
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4519)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4563)
       at android.app.ActivityThread.-wrap21(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1779)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:7000)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

--

Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=27520, result=-1, data=null} to activity {com.softpal.gamya/com.gun0912.tedonactivityresult.ProxyActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4519)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4563)
       at android.app.ActivityThread.-wrap21(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1779)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:7000)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
       at android.media.MediaScannerConnection.<init>(MediaScannerConnection.java:107)
       at android.media.MediaScannerConnection.scanFile(MediaScannerConnection.java:315)
       at gun0912.tedbottompicker.TedBottomSheetDialogFragment.onActivityResultCamera(TedBottomSheetDialogFragment.java:550)
       at gun0912.tedbottompicker.TedBottomSheetDialogFragment.access$2000(TedBottomSheetDialogFragment.java:61)
       at gun0912.tedbottompicker.TedBottomSheetDialogFragment$5.onActivityResult(TedBottomSheetDialogFragment.java:413)
       at com.gun0912.tedonactivityresult.ProxyActivity.onActivityResult(ProxyActivity.java:53)
       at android.app.Activity.dispatchActivityResult(Activity.java:7638)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4515)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4563)
       at android.app.ActivityThread.-wrap21(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1779)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:7000)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by ParkSangGwon** [comment]
@emad3oon please show me sample code, not error log
