### ISSUE TITLE
NullPointerException while selecting Google photo

### ISSUE THREAD

**Issue by garage-sale** [ParkSangGwon/TedBottomPicker#129]
Content URI is: content://com.google.android.apps.photos.contentprovider/0/1/mediakey%3A%2Flocal%253A6c569636-fc1d-4a66-865c-3654544a06de/ORIGINAL/NONE/image%2Fjpeg/127765016
I think the issue is in the following function in RealPathUtil:
public static boolean isGooglePhotosUri(Uri uri) {
        return "com.google.android.apps.photos.content".equals(uri
                .getAuthority());
}

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.x.y, PID: 25840
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=17724, result=-1, data=Intent { dat=content://com.google.android.apps.photos.contentprovider/0/1/mediakey:/local%3A6c569636-fc1d-4a66-865c-3654544a06de/ORIGINAL/NONE/image/jpeg/127765016 flg=0x1 clip={text/uri-list U:content://com.google.android.apps.photos.contentprovider/0/1/mediakey%3A%2Flocal%253A6c569636-fc1d-4a66-865c-3654544a06de/ORIGINAL/NONE/image%2Fjpeg/127765016} }} to activity {com.x.y/com.gun0912.tedonactivityresult.ProxyActivity}: java.lang.NullPointerException: uriString
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4360)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4402)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NullPointerException: uriString
        at android.net.Uri$StringUri.<init>(Uri.java:490)
        at android.net.Uri$StringUri.<init>(Uri.java:480)
        at android.net.Uri.parse(Uri.java:452)
        at gun0912.tedbottompicker.TedBottomSheetDialogFragment.onActivityResultGallery(TedBottomSheetDialogFragment.java:584)
        at gun0912.tedbottompicker.TedBottomSheetDialogFragment.access$2100(TedBottomSheetDialogFragment.java:61)
        at gun0912.tedbottompicker.TedBottomSheetDialogFragment$6.onActivityResult(TedBottomSheetDialogFragment.java:511)
        at com.gun0912.tedonactivityresult.ProxyActivity.onActivityResult(ProxyActivity.java:53)
        at android.app.Activity.dispatchActivityResult(Activity.java:7454)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4353)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4402) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by john-lanticse** [comment]
yes. +1 on this. I'm also getting errors like this.

**Comment by uc3-bfrs** [comment]
same here


caused by java.lang.NullPointerException: uriString
       at android.net.Uri$StringUri.<init>(Uri.java:490)
       at android.net.Uri$StringUri.<init>(Uri.java:480)
       at android.net.Uri.parse(Uri.java:452)
       at gun0912.tedbottompicker.TedBottomSheetDialogFragment.onActivityResultGallery(TedBottomSheetDialogFragment.java:584)
       at gun0912.tedbottompicker.TedBottomSheetDialogFragment.access$2100(TedBottomSheetDialogFragment.java:61)
       at gun0912.tedbottompicker.TedBottomSheetDialogFragment$6.onActivityResult(TedBottomSheetDialogFragment.java:511)
       at com.gun0912.tedonactivityresult.ProxyActivity.onActivityResult(ProxyActivity.java:53)
       at android.app.Activity.dispatchActivityResult(Activity.java:7454)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4375)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4424)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1818)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6762)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
