### ISSUE TITLE
Open Camera throws exception on android 10

### ISSUE THREAD

**Issue by MoaazElneshawy** [ParkSangGwon/TedBottomPicker#139]
grant permissions for camera and storage 
1- images don't load
2- got that exception if i click on camera icon
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.spark.mularepair, PID: 20725
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getCanonicalPath()' on a null object reference
        at androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:748)
        at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:438)
        at gun0912.tedbottompicker.TedBottomSheetDialogFragment.startCameraIntent(TedBottomSheetDialogFragment.java:397)
        at gun0912.tedbottompicker.TedBottomSheetDialogFragment.access$1100(TedBottomSheetDialogFragment.java:61)
        at gun0912.tedbottompicker.TedBottomSheetDialogFragment$3.onItemClick(TedBottomSheetDialogFragment.java:254)
        at gun0912.tedbottompicker.adapter.GalleryAdapter$1.onClick(GalleryAdapter.java:196)
        at android.view.View.performClick(View.java:7125)
        at android.view.View.performClickInternal(View.java:7102)
        at android.view.View.access$3500(View.java:801)
        at android.view.View$PerformClick.run(View.java:27336)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by MoaazElneshawy** [comment]
<uses-permission
        android:name="android.permission.WRITE_EXTERNAL_STORAGE"
        tools:ignore="ScopedStorage" />
