### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException

### ISSUE THREAD

**Issue by CPstudy** [ParkSangGwon/TedBottomPicker#143]
```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=37310, result=-1, data=Intent { dat=비밀 flg=0x1 (has extras) }} to activity {비밀구간.tedonactivityresult.ProxyActivity}: java.lang.NullPointerException: uriString
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4610)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4652)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7050)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

```
Caused by java.lang.NullPointerException: uriString
       at android.net.Uri$StringUri.<init>(Uri.java:490)
       at android.net.Uri$StringUri.<init>(Uri.java:480)
       at android.net.Uri.parse(Uri.java:452)
       at gun0912.tedbottompicker.TedBottomSheetDialogFragment.onActivityResultGallery(TedBottomSheetDialogFragment.java:584)
       at gun0912.tedbottompicker.TedBottomSheetDialogFragment.access$2100(TedBottomSheetDialogFragment.java:61)
       at gun0912.tedbottompicker.TedBottomSheetDialogFragment$6.onActivityResult(TedBottomSheetDialogFragment.java:511)
       at com.gun0912.tedonactivityresult.ProxyActivity.onActivityResult(ProxyActivity.java:53)
       at android.app.Activity.dispatchActivityResult(Activity.java:7762)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4603)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4652)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7050)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

이러한 오류가 나는 이유가 무엇인가요?

**Comment by zoelounge** [comment]
I have the same problem for this device: Samsung, xiaomi, motorola, asus.
There is a fix? Anyone know anything more?
Thanks ;-)
