### ISSUE TITLE
NullPointerException when taking a photo in landscape mode

### ISSUE THREAD

**Issue by blunden** [ParkSangGwon/TedBottomPicker#23]
Whenever I take an image using that option and click the blue checkmark button to select it while being rotated to landscape I get the following exception. For some reason it seems the cameraImageUri variable is null in onActivityResultCamera(final Uri cameraImageUri) when in landscape.

> Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=65537, result=-1, data=Intent {  }} to activity {CENSORED/CENSORED.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getPath()' on a null object reference
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4089)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3403)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3469) 
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2732) 
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4519) 
       at android.app.ActivityThread.-wrap19(ActivityThread.java) 
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1483) 
       at android.os.Handler.dispatchMessage(Handler.java:102) 
       at android.os.Looper.loop(Looper.java:154) 
       at android.app.ActivityThread.main(ActivityThread.java:6126) 
       at java.lang.reflect.Method.invoke(Native Method) 
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
       Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getPath()' on a null object reference
       at gun0912.tedbottompicker.TedBottomPicker.onActivityResultCamera(TedBottomPicker.java:479)
       at gun0912.tedbottompicker.TedBottomPicker.onActivityResult(TedBottomPicker.java:465)
       at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
       at CENSORED.MainActivity.onActivityResult(MainActivity.java:885)
       at android.app.Activity.dispatchActivityResult(Activity.java:6932)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4085)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3403) 
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3469) 
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2732) 
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4519) 
       at android.app.ActivityThread.-wrap19(ActivityThread.java) 
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1483) 
       at android.os.Handler.dispatchMessage(Handler.java:102) 
       at android.os.Looper.loop(Looper.java:154) 
       at android.app.ActivityThread.main(ActivityThread.java:6126) 
       at java.lang.reflect.Method.invoke(Native Method) 
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by ParkSangGwon** [comment]
@blunden 
Thank you.
This issue solved at 1.0.9 version.

**Comment by blunden** [comment]
Thanks, I'll check it out.
