### ISSUE TITLE
Camera not working in Nougat devices.

### ISSUE THREAD

**Issue by jubin-successive** [ParkSangGwon/TedBottomPicker#24]
Hi, I'm getting this error when I'm opening the camera window.

Please update the library or let us know a solution.
Thanks in advance

FATAL EXCEPTION: main
                                                                        Process: com.successive.khoyapaya, PID: 2337
                                                                        android.os.FileUriExposedException: file:///storage/emulated/0/Pictures/JPEG_20170208115930_1243992149.jpg exposed beyond app through ClipData.Item.getUri()
                                                                            at android.os.StrictMode.onFileUriExposed(StrictMode.java:1813)
                                                                            at android.net.Uri.checkFileUriExposed(Uri.java:2360)
                                                                            at android.content.ClipData.prepareToLeaveProcess(ClipData.java:832)
                                                                            at android.content.Intent.prepareToLeaveProcess(Intent.java:8957)
                                                                            at android.content.Intent.prepareToLeaveProcess(Intent.java:8942)
                                                                            at android.app.Instrumentation.execStartActivity(Instrumentation.java:1583)
                                                                            at android.app.Activity.startActivityForResult(Activity.java:4228)
                                                                            at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
                                                                            at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
                                                                            at android.support.v4.app.ActivityCompatJB.startActivityForResult(ActivityCompatJB.java:30)
                                                                            at android.support.v4.app.ActivityCompat.startActivityForResult(ActivityCompat.java:146)
                                                                            at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:937)
                                                                            at android.support.v4.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:1047)
                                                                            at android.support.v4.app.Fragment.startActivityForResult(Fragment.java:954)
                                                                            at android.support.v4.app.Fragment.startActivityForResult(Fragment.java:943)
                                                                            at gun0912.tedbottompicker.TedBottomPicker.startCameraIntent(TedBottomPicker.java:190)
                                                                            at gun0912.tedbottompicker.TedBottomPicker.access$000(TedBottomPicker.java:45)
                                                                            at gun0912.tedbottompicker.TedBottomPicker$2.onItemClick(TedBottomPicker.java:139)
                                                                            at gun0912.tedbottompicker.adapter.ImageGalleryAdapter$1.onClick(ImageGalleryAdapter.java:131)
                                                                            at android.view.View.performClick(View.java:5612)
                                                                            at android.view.View$PerformClick.run(View.java:22285)
                                                                            at android.os.Handler.handleCallback(Handler.java:751)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by ParkSangGwon** [comment]
@jubin-successive I think that is `FileProvider` issue.
(https://developer.android.com/about/versions/nougat/android-7.0-changes.html#perm)
But that issue solved at v1.0.8.
What is your library version?
Let me know.

**Comment by jubin-successive** [comment]
Thanks, the issue was resolved when I updated the version.

**Comment by ParkSangGwon** [comment]
@jubin-successive Glad to hear. Happy coding!!
