### ISSUE TITLE
Android Noga Camera Issue

### ISSUE THREAD

**Issue by AhmedBadrSayed** [ParkSangGwon/TedBottomPicker#39]
I am facing a problem when i try to capture image from camera if the target sdk is 24 or above the app crashs known that it works well with least android versions and here is the exception

```
android.os.FileUriExposedException: file:///storage/emulated/0/Pictures/JPEG_20170330135039_1219814178.jpg exposed beyond app through ClipData.Item.getUri()
                                                                             at android.os.StrictMode.onFileUriExposed(StrictMode.java:1799)
                                                                             at android.net.Uri.checkFileUriExposed(Uri.java:2346)
                                                                             at android.content.ClipData.prepareToLeaveProcess(ClipData.java:832)
                                                                             at android.content.Intent.prepareToLeaveProcess(Intent.java:8909)
                                                                             at android.content.Intent.prepareToLeaveProcess(Intent.java:8894)
                                                                             at android.app.Instrumentation.execStartActivity(Instrumentation.java:1517)
                                                                             at android.app.Activity.startActivityForResult(Activity.java:4224)
                                                                             at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
                                                                             at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
                                                                             at android.support.v4.app.ActivityCompatJB.startActivityForResult(ActivityCompatJB.java:30)
                                                                             at android.support.v4.app.ActivityCompat.startActivityForResult(ActivityCompat.java:146)
                                                                             at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:937)
                                                                             at android.support.v4.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:1047)
                                                                             at android.support.v4.app.Fragment.startActivityForResult(Fragment.java:959)
                                                                             at android.support.v4.app.Fragment.startActivityForResult(Fragment.java:948)
                                                                             at gun0912.tedbottompicker.TedBottomPicker.startCameraIntent(TedBottomPicker.java:189)
                                                                             at gun0912.tedbottompicker.TedBottomPicker.access$000(TedBottomPicker.java:44)
                                                                             at gun0912.tedbottompicker.TedBottomPicker$2.onItemClick(TedBottomPicker.java:138)
                                                                             at gun0912.tedbottompicker.adapter.ImageGalleryAdapter$1.onClick(ImageGalleryAdapter.java:131)
                                                                             at android.view.View.performClick(View.java:5609)
                                                                             at android.view.View$PerformClick.run(View.java:22262)
                                                                             at android.os.Handler.handleCallback(Handler.java:751)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by ParkSangGwon** [comment]
@AhmedBadrSayed Nougat's file path issue is already solved at recent version.
What is your library version?

**Comment by AhmedBadrSayed** [comment]
@ParkSangGwon  Thanks for replying, you are right the problem was in the library version I updated 

> compile 'gun0912.ted:tedpermission:1.0.3'

 and it worked fine
