### ISSUE TITLE
Issue Runtime Exception

### ISSUE THREAD

**Issue by GuillemRoca** [ParkSangGwon/TedBottomPicker#40]
Hello,

First of all thanks for the awesome library.

Recently I have encountered the follwing error in Fabric because some users found it.

`Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{es....}: java.lang.NullPointerException: Attempt to read from field 'int gun0912.tedbottompicker.c$a.n' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
       at android.app.ActivityThread.access$900(ActivityThread.java:150)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by java.lang.NullPointerException: Attempt to read from field 'int gun0912.tedbottompicker.c$a.n' on a null object reference
       at gun0912.tedbottompicker.TedBottomPicker.show(Unknown Source)
       at android.support.v4.app.DialogFragment.getDialog(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.modifiesAlpha(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.getBackStackEntryCount(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.modifiesAlpha(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.findFragmentUnder(Unknown Source)
       at android.support.v4.app.FragmentController.dispatchActivityCreated(Unknown Source)
       at android.support.v4.app.FragmentActivity.onStart(Unknown Source)
       at android.support.v7.app.AppCompatActivity.onStart(Unknown Source)
       at com.Activity.onStart(Unknown Source)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238)
       at android.app.Activity.performStart(Activity.java:6302)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
       at android.app.ActivityThread.access$900(ActivityThread.java:150)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616))`

I'm using the version 'gun0912.ted:tedbottompicker:1.0.10'

Thanks

**Comment by GuillemRoca** [comment]
The code is ofuscated with proguard beacuse it's a production build so if it's difficult to find I will try to reproduce it in develop, which I was unable to reproduce.

**Comment by GuillemRoca** [comment]
I think this error is the same as detailed in #38. Need further investigation. I applied the fix in `v1.0.11` Hope it solves the issue

**Comment by ParkSangGwon** [comment]
@GuillemRoca How about now?
Did you solve this problem?
Please tell me result

**Comment by ParkSangGwon** [comment]
No answer, close

**Comment by Midhilaj** [comment]
no ,still problem so trying to change this libary
