### ISSUE TITLE
 android.os.FileUriExposedException: file:///storage/emulated/0/Pictures/JPEG_20170403160746_742136310.jpg exposed beyond app through ClipData.Item.getUri()

### ISSUE THREAD

**Issue by yunhoi129** [ParkSangGwon/TedBottomPicker#41]
issue at API LEVEL 24 

 private File getImageFile() {
        // Create an image file name
        File imageFile = null;
        try {
            String timeStamp = new SimpleDateFormat("yyyyMMddHHmmss", Locale.getDefault()).format(new Date());
            String imageFileName = "JPEG_" + timeStamp + "_";
            File storageDir = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES);

            imageFile = File.createTempFile(
                    imageFileName,  /* prefix */
                    ".jpg",         /* suffix */
                    storageDir      /* directory */
            );

            // Save a file: path for use with ACTION_VIEW intents
            cameraImageUri = Uri.fromFile(imageFile);

i think.. Uri.fromFile should be changed to like below

 FileProvider.getUriForFile(context, context.getApplicationContext().getPackageName() + ".provider", createImageFile());

**Comment by yunhoi129** [comment]
Sorry. it's my fault i used low version.. thx.

**Comment by ParkSangGwon** [comment]
@yunhoi129 Thanks

**Comment by sivabramha** [comment]
Using getExternalFilesDir(null).getAbsolutePath() we can solve your problem

**Comment by parshwa1596** [comment]
android.os.FileUriExposedException: file:///storage/emulated/0/Documents/Patidar.pdf exposed beyond app through Intent.getData()
        at android.os.StrictMode.onFileUriExposed(StrictMode.java:1960)
        at android.net.Uri.checkFileUriExposed(Uri.java:2362)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:9901)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:9853)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1612)
        at android.app.Activity.startActivityForResult(Activity.java:4555)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:767)
        at android.app.Activity.startActivityForResult(Activity.java:4513)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:754)
        at android.app.Activity.startActivity(Activity.java:4874)
        at android.app.Activity.startActivity(Activity.java:4842)
        at com.patidar.marriagebureau.Activities.Printprofile.previewPdf(Printprofile.java:501)
        at com.patidar.marriagebureau.Activities.Printprofile.createPdf(Printprofile.java:486)
        at com.patidar.marriagebureau.Activities.Printprofile.createPdfWrapper(Printprofile.java:416)
        at com.patidar.marriagebureau.Activities.Printprofile.access$000(Printprofile.java:65)
        at com.patidar.marriagebureau.Activities.Printprofile$1.onClick(Printprofile.java:171)
        at android.view.View.performClick(View.java:6312)

i got these error what can i do?

**Comment by abdullaabdulla422** [comment]
you need to add provider in your manifest

**Comment by momodu** [comment]
I had this same issue but it is now resolved. 
Please check this link: https://www.codeproject.com/Articles/1273560/Xamarin-Forms-Share-Media-With-Other-Apps
