### ISSUE TITLE
when selecting camera options app crashes

### ISSUE THREAD

**Issue by VMVishnuMohan** [ParkSangGwon/TedBottomPicker#44]
http://stackoverflow.com/questions/43449481/android-app-crashes-when-selecting-the-camera-options-from-tedbottompicker-libra

**Comment by VMVishnuMohan** [comment]
solved issue by updating the library version to     compile 'gun0912.ted:tedbottompicker:1.0.11'

**Comment by vishnumohan345** [comment]
FATAL EXCEPTION: main
                                                            Process: com.beco.ibeco, PID: 28124
                                                            java.lang.NullPointerException: file
                                                                at android.net.Uri.fromFile(Uri.java:453)
                                                                at gun0912.tedbottompicker.TedBottomPicker.startCameraIntent(TedBottomPicker.java:188)
                                                                at gun0912.tedbottompicker.TedBottomPicker.access$000(TedBottomPicker.java:44)
                                                                at gun0912.tedbottompicker.TedBottomPicker$2.onItemClick(TedBottomPicker.java:138)
                                                                at gun0912.tedbottompicker.adapter.ImageGalleryAdapter$1.onClick(ImageGalleryAdapter.java:131)
                                                                at android.view.View.performClick(View.java:5716)
                                                                at android.view.View$PerformClick.run(View.java:22596)
                                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at android.os.Looper.loop(Looper.java:148)
                                                                at android.app.ActivityThread.main(ActivityThread.java:7325)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

http://stackoverflow.com/questions/43449481/android-app-crashes-when-selecting-the-camera-options-from-tedbottompicker-libra
