### ISSUE TITLE
Crash when we select Corrupted or deleted image

### ISSUE THREAD

**Issue by kksingla** [ParkSangGwon/TedBottomPicker#45]
I have found the solution. I make a pull request already. Please review

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1888, result=0, data=null} to activity {photo.booth.app/photo.booth.app.PhotoboothActivity}: java.lang.NullPointerException
    at android.app.ActivityThread.deliverResults(ActivityThread.java:2934)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:2986)
    at android.app.ActivityThread.access$2000(ActivityThread.java:132)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1068)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:150)
    at android.app.ActivityThread.main(ActivityThread.java:4293)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:507)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:849)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:607)
    at dalvik.system.NativeStart.main(Native Method)
    Caused by: java.lang.NullPointerException
    at photo.booth.app.PhotoboothActivity.onActivityResult(PhotoboothActivity.java:76)
    at android.app.Activity.dispatchActivityResult(Activity.java:4108)
    at android.app.ActivityThread.deliverResults(ActivityThread.java:2930)

**Comment by StephenMilone** [comment]
I think this would also fix an issue I had today, my trace is a little different:

Caused by java.lang.NullPointerException: uriString
android.net.Uri$StringUri.<init> (Uri.java:475)
android.net.Uri$StringUri.<init> (Uri.java)
android.net.Uri.parse (Uri.java:437)
gun0912.tedbottompicker.TedBottomPicker.onActivityResultGallery (TedBottomPicker.java:566)
gun0912.tedbottompicker.TedBottomPicker.onActivityResult (TedBottomPicker.java:515)
android.support.v4.app.FragmentActivity.onActivityResult (FragmentActivity.java:164)

**Comment by cioraneanu** [comment]
In my crash reports I have the same exact stack trace as @StephenMilone 
Any clues on this? :)

**Comment by kksingla** [comment]
May i close this issue?
