### ISSUE TITLE
Camera does not ask for permission, app crashes directly

### ISSUE THREAD

**Issue by lsw19921030** [ParkSangGwon/TedBottomPicker#62]
I expect when user clicks on the camera tile, it should prompt and ask user for permission. However, the app simply crashes.

FATAL EXCEPTION: main Process: com.ucardnew2, PID: 16766
                                                               java.lang.SecurityException: Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.sonyericsson.android.camera/.MultiWindowActivity clip={text/uri-list U:content://com.ucardnew2.provider/external_files/Pictures/JPEG_20170822123828_999896944.jpg} (has extras) } from ProcessRecord{d9a8f35 16766:com.ucardnew2/u0a318} (pid=16766, uid=10318) with revoked permission android.permission.CAMERA
                                                                   at android.os.Parcel.readException(Parcel.java:1689)
                                                                   at android.os.Parcel.readException(Parcel.java:1641)
                                                                   at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:3128)
                                                                   at android.app.Instrumentation.execStartActivity(Instrumentation.java:1520)
                                                                   at android.app.Activity.startActivityForResult(Activity.java:4266)
                                                                   at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
                                                                   at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:65)
                                                                   at android.support.v4.app.ActivityCompat.startActivityForResult(ActivityCompat.java:152)
                                                                   at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:789)
                                                                   at android.support.v4.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:898)
                                                                   at android.support.v4.app.Fragment.startActivityForResult(Fragment.java:1013)
                                                                   at android.support.v4.app.Fragment.startActivityForResult(Fragment.java:1002)
                                                                   at gun0912.tedbottompicker.TedBottomPicker.startCameraIntent(TedBottomPicker.java:423)
                                                                   at gun0912.tedbottompicker.TedBottomPicker.access$100(TedBottomPicker.java:57)
                                                                   at gun0912.tedbottompicker.TedBottomPicker$3.onItemClick(TedBottomPicker.java:275)
                                                                   at gun0912.tedbottompicker.adapter.ImageGalleryAdapter$1.onClick(ImageGalleryAdapter.java:180)
                                                                   at android.view.View.performClick(View.java:5685)
                                                                   at android.view.View$PerformClick.run(View.java:22481)
                                                                   at android.os.Handler.handleCallback(Handler.java:751)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:241)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6274)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by ParkSangGwon** [comment]
Please read `Readme`
First of all, you have to grant permission.
https://github.com/ParkSangGwon/TedBottomPicker#1-check-permission

**Comment by lsw19921030** [comment]
You need runtime permission! Run time permission is needed since Android 6.0!!!!
We users can handle run time permission of external storage before entering your tile, but inside the tile, your library needs to handle camera run time permission.
