### ISSUE TITLE
on click of camera app crash

### ISSUE THREAD

**Issue by shrutinupur** [ParkSangGwon/TedBottomPicker#68]
in api 19 on click of camera app crash

**Comment by ParkSangGwon** [comment]
@shrutinupur 
Let me know crash log

**Comment by shrutinupur** [comment]
its only crash in RedMi 1s Api 19 kitkat
 FATAL EXCEPTION: main
                                                   Process: merchant.gpdock.com.gpdockmerchant, PID: 10524
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{merchant.gpdock.com.gpdockmerchant/merchant.gpdock.com.gpdockmerchant.Activity.HomeActivity}: java.lang.NullPointerException
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2200)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249)
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:141)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5052)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
                                                       at dalvik.system.NativeStart.main(Native Method)
                                                    Caused by: java.lang.NullPointerException
                                                       at gun0912.tedbottompicker.TedBottomPicker.setTitle(TedBottomPicker.java:483)
                                                       at gun0912.tedbottompicker.TedBottomPicker.setupDialog(TedBottomPicker.java:168)
                                                       at android.support.v4.app.DialogFragment.getLayoutInflater(DialogFragment.java:315)
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
                                                       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                       at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2900)
                                                       at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
                                                       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:603)
                                                       at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
                                                       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
                                                       at android.app.Activity.performStart(Activity.java:5252)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2173)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:141) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:136) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5052) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612) 
                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by shrutinupur** [comment]
its working good in other phone

**Comment by shrutinupur** [comment]
it set image from gallery only crash on when i click image from camera

**Comment by fabads** [comment]
Also had a crash ... But just because CAMERA permissions were missing.

**Comment by ParkSangGwon** [comment]
@fabads Thanks your comment.
@shrutinupur Did you check your `CAMERA` permission?

**Comment by mohanbright** [comment]
Also had a crash ... But just because CAMERA permissions were missing. and permissions are enabled
