### ISSUE TITLE
NoSuchMethodError when trying to launch TedBottomPicker

### ISSUE THREAD

**Issue by gyugyu90** [ParkSangGwon/TedBottomPicker#70]
Hi, I found this bug when I tried TedBottomPicker from my Sony Xperia device.
I am using glide library version 4.2.0 for my project.

Let me show you the error log
`
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.lovelyfnt.ricohost_android, PID: 5827
                                                                              java.lang.NoSuchMethodError: No virtual method load(Landroid/net/Uri;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/com.lovelyfnt.ricohost_android-1/split_lib_dependencies_apk.apk)
                                                                                  at gun0912.tedbottompicker.adapter.GalleryAdapter.onBindViewHolder(GalleryAdapter.java:163)
                                                                                  at gun0912.tedbottompicker.adapter.GalleryAdapter.onBindViewHolder(GalleryAdapter.java:32)
                                                                                  at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6482)
                                                                                  at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6515)
                                                                                  at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5458)
                                                                                  at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5724)
                                                                                  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5563)
                                                                                  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5559)
                                                                                  at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2229)
                                                                                  at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
                                                                                  at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1516)
                                                                                  at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:608)
                                                                                  at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                                  at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3693)
                                                                                  at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3109)
                                                                                  at android.view.View.measure(View.java:18880)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                                  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                                  at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                                  at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                                  at android.view.View.measure(View.java:18880)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                  at android.view.View.measure(View.java:18880)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                                  at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:714)
                                                                                  at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:786)
                                                                                  at android.view.View.measure(View.java:18880)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                  at android.view.View.measure(View.java:18880)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                  at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                                  at android.view.View.measure(View.java:18880)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                  at android.view.View.measure(View.java:18880)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                  at android.view.View.measure(View.java:18880)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                                  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                                  at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                                  at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                                  at android.view.View.measure(View.java:18880)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                  at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2650)
                                                                              	at android.view.View.measu
`

any ideas about this?

**Comment by gyugyu90** [comment]
I downgraded Glide version to 3 and it works alright..
Do you by any chance get a reason for this?

**Comment by ParkSangGwon** [comment]
You can use `setImageProvider()`
Read this.
https://github.com/ParkSangGwon/TedBottomPicker#common
