### ISSUE TITLE
Glide Conflict 

### ISSUE THREAD

**Issue by kksingla** [ParkSangGwon/TedBottomPicker#73]
Glide removed a method called "dontAnimate()" in 4.x

java.lang.NoSuchMethodError: No virtual method load(Landroid/net/Uri;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/com.servicio-2/split_lib_dependencies_apk.apk)
                                                                  at gun0912.tedbottompicker.adapter.ImageGalleryAdapter.onBindViewHolder(ImageGalleryAdapter.java:144)
                                                                  at gun0912.tedbottompicker.adapter.ImageGalleryAdapter.onBindViewHolder(ImageGalleryAdapter.java:32)
                                                                  at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6508)
                                                                  at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6541)
                                                                  at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5484)
                                                                  at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5750)
                                                                  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5589)
                                                                  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5585)
                                                                  at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2231)
                                                                  at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
                                                                  at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
                                                                  at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:610)
                                                                  at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                  at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3719)
                                                                  at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3135)
                                                                  at android.view.View.measure(View.java:18794)
                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                  at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                  at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                  at android.view.View.measure(View.java:18794)
                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                  at android.view.View.measure(View.java:18794)
                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                  at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:719)
                                                                  at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:791)
                                                                  at android.view.View.measure(View.java:18794)
                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                  at android.view.View.measure(View.java:18794)
                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                  at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                  at android.view.View.measure(View.java:18794)

**Comment by ParkSangGwon** [comment]
@kksingla 
Please read `README`
If you want use custom your image loader, you have to use `setImageProvider(ImageProvider)`.

**Comment by thdeodls85** [comment]
TedBottomPicker.ImageProvider provider = new TedBottomPicker.ImageProvider()
                    {
                        @Override
                        public void onProvideImage(ImageView imageView, Uri imageUri)
                        {
                            RequestOptions options = new RequestOptions().centerCrop();
                            Glide.with(CheckActivity.this).load(imageUri).apply(options).into(imageView);
                        }
                    };

setImageProvider(provider);
