### ISSUE TITLE
RunTime Error

### ISSUE THREAD

**Issue by Ruhallah93** [ParkSangGwon/TedBottomPicker#74]
Hi sir
I have got this crash, please help me

```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=720898, result=-1, data=Intent { dat=content://media/external/images/media/257777 flg=0x1 }} to activity {com.mobile.melkplus/com.mobile.melkplus.MainActivity}: java.lang.NullPointerException: uriString
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3864)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3907)
	at android.app.ActivityThread.access$1300(ActivityThread.java:182)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1523)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5662)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by: java.lang.NullPointerException: uriString
	at android.net.Uri$StringUri.<init>(Uri.java:470)
	at android.net.Uri$StringUri.<init>(Uri.java:460)
	at android.net.Uri.parse(Uri.java:432)
	at gun0912.tedbottompicker.TedBottomPicker.a(SourceFile:566)
	at gun0912.tedbottompicker.TedBottomPicker.onActivityResult(SourceFile:515)
	at android.support.v4.app.FragmentActivity.onActivityResult(SourceFile:151)
	at android.app.Activity.dispatchActivityResult(Activity.java:6310)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3860)
	... 10 more
```

**Comment by ParkSangGwon** [comment]
@Ruhallah93 
Show me your sample code.
