### ISSUE TITLE
Glide error

### ISSUE THREAD

**Issue by rlawlwoong** [ParkSangGwon/TedBottomPicker#76]
I use  compile 'com.github.bumptech.glide:glide:4.0.0' and when I use TedBottomPicker App crashes with error below

12-29 17:43:18.528 14928-14928/kr.coops.com E/UncaughtException: java.lang.NoSuchMethodError: No virtual method load(Landroid/net/Uri;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/kr.coops.com-2/split_lib_dependencies_apk.apk:classes39.dex)
                                                                     at gun0912.tedbottompicker.adapter.GalleryAdapter.onBindViewHolder(GalleryAdapter.java:163)
                                                                     at gun0912.tedbottompicker.adapter.GalleryAdapter.onBindViewHolder(GalleryAdapter.java:32)
                                                                     at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6356)
                                                                     at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6389)
                                                                     at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5335)
                                                                     at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5598)
                                                                     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                                     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                                     at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                                     at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
                                                                     at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                     at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                                     at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                     at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                                                     at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3025)
                                                                     at android.view.View.measure(View.java:21121)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6462)
                                                                     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                     at android.view.View.measure(View.java:21121)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6462)
                                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                     at android.view.View.measure(View.java:21121)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6462)
                                                                     at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:714)
                                                                     at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:786)
                                                                     at android.view.View.measure(View.java:21121)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6462)
                                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                     at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                     at android.view.View.measure(View.java:21121)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6462)
                                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                     at android.view.View.measure(View.java:21121)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6462)
                                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                     at android.view.View.measure(View.java:21121)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6462)
                                                                     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                     at android.view.View.measure(View.java:21121)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6462)
                                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                     at com.android.internal.policy.DecorView.onMeasure(DecorView.java:897)
                                                                     at android.view.View.measure(View.java:21121)
                                                                     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2625)
                                                                     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1677)
12-29 17:43:18.528 14928-14928/kr.coops.com E/UncaughtException:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1928)
                                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1550)
                                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7189)
                                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:959)
                                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:734)
                                                                     at android.view.Choreographer.doFrame(Choreographer.java:670)
                                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:945)
                                                                     at android.os.Handler.handleCallback(Handler.java:751)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by bpappin** [comment]
The current version hasn't been upgraded. See issue #77
