### ISSUE TITLE
NullPointerException at onActivityResult

### ISSUE THREAD

**Issue by patriziolerede** [ParkSangGwon/TedBottomPicker#79]
Hi , I've founded a nullpointerexception. I attached the stacktrace.

```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=65538, result=-1, data=Intent { dat=content://com.google.android.apps.photos.contentprovider/0/1/mediakey:/local%3A9f509056-9ce4-4cf2-93cd-537a957e606b/ORIGINAL/NONE/1957108382 flg=0x1 clip={text/uri-list U:content://com.google.android.apps.photos.contentprovider/0/1/mediakey%3A%2Flocal%253A9f509056-9ce4-4cf2-93cd-537a957e606b/ORIGINAL/NONE/1957108382} }} to activity {****.ProfileEditActivity}: java.lang.NullPointerException: uriString
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4268)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4312)
       at android.app.ActivityThread.-wrap19(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1644)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by java.lang.NullPointerException: uriString
       at android.net.Uri$StringUri.<init>(Uri.java:476)
       at android.net.Uri$StringUri.<init>(Unknown Source)
       at android.net.Uri.parse(Uri.java:438)
       at petrov.kristiyan.TedBottomPicker.onActivityResultGallery(TedBottomPicker.java:561)
       at petrov.kristiyan.TedBottomPicker.onActivityResult(TedBottomPicker.java:511)
       at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:149)
       at *******.onActivityResult(ProfileEditActivity.java:260)
       at android.app.Activity.dispatchActivityResult(Activity.java:7266)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4264)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4312)
       at android.app.ActivityThread.-wrap19(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1644)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```
Thanks

**Comment by bpappin** [comment]
What phone and version of Android are you using?
This sounds like a Samsung thing.

**Comment by patriziolerede** [comment]
Huawei Nexus 6P with Android 8.1.0

**Comment by ParkSangGwon** [comment]
@patriziolerede I will check it.

**Comment by hendrawd** [comment]
any update?

**Comment by ParkSangGwon** [comment]
Please check `v1.2.0`
