### ISSUE TITLE
setTitle give null pointer exception

### ISSUE THREAD

**Issue by enggazzar** [ParkSangGwon/TedBottomPicker#88]

**Comment by ParkSangGwon** [comment]
Thanks. I will check

**Comment by jessejohnson** [comment]
Hello Park, here's a stacktrace I got from Crashlytics

`Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.my.app.package/com.my.app.ui.ProfileActivity}: java.lang.NullPointerException: Attempt to read from field 'boolean dependencies.ebg$a.r' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2534)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2608)
       at android.app.ActivityThread.access$800(ActivityThread.java:178)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5637)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)`

`Caused by java.lang.NullPointerException: Attempt to read from field 'boolean dependencies.ebg$a.r' on a null object reference
       at gun0912.tedbottompicker.TedBottomPicker.setTitle(Unknown Source:535)
       at gun0912.tedbottompicker.TedBottomPicker.setupDialog(Unknown Source:171)
       at android.support.v4.app.DialogFragment.onGetLayoutInflater(Unknown Source:331)
       at android.support.v4.app.Fragment.performGetLayoutInflater(Unknown Source:1226)
       at android.support.v4.app.FragmentManagerImpl.moveToState(Unknown Source:1428)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(Unknown Source:1759)
       at android.support.v4.app.FragmentManagerImpl.moveToState(Unknown Source:1827)
       at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(Unknown Source:3244)
       at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(Unknown Source:3200)
       at android.support.v4.app.FragmentController.dispatchActivityCreated(Unknown Source:195)
       at android.support.v4.app.FragmentActivity.onStart(Unknown Source:597)
       at android.support.v7.app.AppCompatActivity.onStart(Unknown Source:177)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1244)
       at android.app.Activity.performStart(Activity.java:6108)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2491)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2608)
       at android.app.ActivityThread.access$800(ActivityThread.java:178)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5637)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)`

**Comment by jessejohnson** [comment]
I'm using version `1.1.0`.
Do you have a changelog I can read to see if this issue has been fixed in a newer version?

**Comment by jessejohnson** [comment]
@ParkSangGwon Any update on this issue?

**Comment by jura73** [comment]
Hello Park, this happens after the application is stopped
	
Reproduce:
	tedbottompickerdemo -> Show Ted Bottom Picker(Single) -> 
(Device) Home -> (Android Studio - Logcat) Terminate Application - > Recent

`29232-29232/gun0912.tedbottompickerdemo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: gun0912.tedbottompickerdemo, PID: 29232
    java.lang.RuntimeException: Unable to start activity ComponentInfo{gun0912.tedbottompickerdemo/gun0912.tedbottompickerdemo.MainActivity}: java.lang.NullPointerException: Attempt to read from field 'boolean gun0912.tedbottompicker.TedBottomPicker$Builder.showTitle' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: java.lang.NullPointerException: Attempt to read from field 'boolean gun0912.tedbottompicker.TedBottomPicker$Builder.showTitle' on a null object reference
        at gun0912.tedbottompicker.TedBottomPicker.setTitle(TedBottomPicker.java:555)
        at gun0912.tedbottompicker.TedBottomPicker.setupDialog(TedBottomPicker.java:172)
        at android.support.v4.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:331)
        at android.support.v4.app.Fragment.performGetLayoutInflater(Fragment.java:1226)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3200)
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:195)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:597)
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
        at android.app.Activity.performStart(Activity.java:6696)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2628)`
