### ISSUE TITLE
can't find superclass or interface com.gun0912.tedonactivityresult.listener.OnActivityResultListener

### ISSUE THREAD

**Issue by Midhilaj** [ParkSangGwon/TedBottomPicker#93]
Warning: gun0912.tedbottompicker.TedBottomPicker$5: can't find superclass or interface com.gun0912.tedonactivityresult.listener.OnActivityResultListener
Warning: gun0912.tedbottompicker.TedBottomPicker$6: can't find superclass or interface com.gun0912.tedonactivityresult.listener.OnActivityResultListener
Warning: gun0912.tedbottompicker.TedBottomPicker: can't find referenced class com.gun0912.tedonactivityresult.TedOnActivityResult
Warning: gun0912.tedbottompicker.TedBottomPicker: can't find referenced class com.gun0912.tedonactivityresult.TedOnActivityResult$Builder
Warning: gun0912.tedbottompicker.TedBottomPicker: can't find referenced class com.gun0912.tedonactivityresult.TedOnActivityResult$Builder
Warning: gun0912.tedbottompicker.TedBottomPicker: can't find referenced class com.gun0912.tedonactivityresult.TedOnActivityResult$Builder
Warning: gun0912.tedbottompicker.TedBottomPicker: can't find referenced class com.gun0912.tedonactivityresult.TedOnActivityResult
Warning: gun0912.tedbottompicker.TedBottomPicker: can't find referenced class com.gun0912.tedonactivityresult.TedOnActivityResult$Builder
Warning: gun0912.tedbottompicker.TedBottomPicker$5: can't find referenced class com.gun0912.tedonactivityresult.listener.OnActivityResultListener
Warning: gun0912.tedbottompicker.TedBottomPicker$5$1: can't find referenced method 'void access$600(gun0912.tedbottompicker.TedBottomPicker)' in program class gun0912.tedbottompicker.TedBottomPicker
Warning: gun0912.tedbottompicker.TedBottomPicker$5$1: can't find referenced field 'android.net.Uri val$cameraImageUri' in program class gun0912.tedbottompicker.TedBottomPicker$5
Warning: gun0912.tedbottompicker.TedBottomPicker$5$1: can't find enclosing method 'void onScanCompleted(java.lang.String,android.net.Uri)' in program class gun0912.tedbottompicker.TedBottomPicker$5
Warning: gun0912.tedbottompicker.TedBottomPicker$6: can't find referenced class com.gun0912.tedonactivityresult.listener.OnActivityResultListener

Error:Execution failed for task ':app:transformClassesWithAndroidGradleClassShrinkerForDebug'.
> Warnings found during shrinking, please use -dontwarn or -ignorewarnings to suppress them.

**Comment by ParkSangGwon** [comment]
@Midhilaj What is your library version?

**Comment by StephenMilone** [comment]
```
import com.gun0912.tedonactivityresult.TedOnActivityResult;
import com.gun0912.tedonactivityresult.listener.OnActivityResultListener;
```

from the new 1.2.1 build, those 2 imports fail and when i start the camera intent it crashes

**Comment by NetoDevel** [comment]
happening the same error with me, @ParkSangGwon

**Comment by theGnartist** [comment]
@StephenMilone @NetoDevel @ParkSangGwon 
Adding 
`implementation 'gun0912.ted:tedonactivityresult:1.0.4'`
to my gradle file fixed this issue.
However, it then brings up a new one
```java.lang.RuntimeException: Unable to start activity ComponentInfo{com.phobio.rodio/com.gun0912.tedonactivityresult.ProxyActivity}: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                      at android.app.ActivityThread.-wrap11(Unknown Source:0)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                      at android.os.Handler.dispatchMessage(Handler.java:105)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6541)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                   Caused by: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
                      at android.app.Activity.onCreate(Activity.java:986)
                      at com.gun0912.tedonactivityresult.ProxyActivity.onCreate(ProxyActivity.java:35)
                      at android.app.Activity.performCreate(Activity.java:6975)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
                      at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
                      at android.os.Handler.dispatchMessage(Handler.java:105) 
                      at android.os.Looper.loop(Looper.java:164) 
                      at android.app.ActivityThread.main(ActivityThread.java:6541) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) ```

**Comment by wayne811** [comment]
happening the same error with me (v1.2.1)

**Comment by theGnartist** [comment]
@wayne811 
Adding
`implementation 'gun0912.ted:tedonactivityresult:1.0.4'`
to your app gradle file will resolve this.

However, an Android O and higher you will likely run into a crash from the portrait orientation in the activityresult dependency.  I have resolved this in a fork here: 
https://github.com/theGnartist/TedRxOnActivityResult/commit/bf620676fed13818b66c5913bf4af0575c360fcb

If you are using jitpack you can can use my fork by adding 
`implementation 'com.github.theGnartist:TedRxOnActivityResult:bf620676fed13818b66c5913bf4af0575c360fcb'`
instead.

**Comment by theGnartist** [comment]
The crash on Android O and higher has been resolved in tedonactivityresult.
Adding `implementation `compile 'gun0912.ted:tedonactivityresult-rx1:1.0.6` to your app gradle file will resolve all issues in this thread.
