### ISSUE TITLE
App crash when clicked on CameraTile

### ISSUE THREAD

**Issue by CodeDem** [ParkSangGwon/TedBottomPicker#96]
Error Trace:
```
 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/gun0912/tedonactivityresult/TedOnActivityResult;
        at gun0912.tedbottompicker.TedBottomPicker.startGalleryIntent(TedBottomPicker.java:536)
        at gun0912.tedbottompicker.TedBottomPicker.access$200(TedBottomPicker.java:63)
        at gun0912.tedbottompicker.TedBottomPicker$3.onItemClick(TedBottomPicker.java:282)
        at gun0912.tedbottompicker.adapter.GalleryAdapter$1.onClick(GalleryAdapter.java:199)
        at android.view.View.performClick(View.java:5215)
        at android.view.View$PerformClick.run(View.java:21193)
        at android.os.Handler.handleCallback(Handler.java:742)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5571)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.gun0912.tedonactivityresult.TedOnActivityResult" on path: DexPathList[[zip file "/data/app/livfitt.app.com-1/base.apk", zip file "/data/app/livfitt.app.com-1/split_lib_dependencies_apk.apk", zip file "/data/app/livfitt.app.com-1/split_lib_slice_0_apk.apk", zip file "/data/app/livfitt.app.com-1/split_lib_slice_1_apk.apk", zip file "/data/app/livfitt.app.com-1/split_lib_slice_2_apk.apk", zip file "/data/app/livfitt.app.com-1/split_lib_slice_3_apk.apk", zip file "/data/app/livfitt.app.com-1/split_lib_slice_4_apk.apk", zip file "/data/app/livfitt.app.com-1/split_lib_slice_5_apk.apk", zip file "/data/app/livfitt.app.com-1/split_lib_slice_6_apk.apk", zip file "/data/app/livfitt.app.com-1/split_lib_slice_7_apk.apk", zip file "/data/app/livfitt.app.com-1/split_lib_slice_8_apk.apk", zip file "/data/app/livfitt.app.com-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/livfitt.app.com-1/lib/arm64, /data/app/livfitt.app.com-1/base.apk!/lib/arm64-v8a, /data/app/livfitt.app.com-1/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/livfitt.app.com-1/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/livfitt.app.com-1/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/livfitt.app.com-1/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/livfitt.app.com-1/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/livfitt.app.com-1/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/livfitt.app.com-1/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/livfitt.app.com-1/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/livfitt.app.com-1/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/livfitt.app.com-1/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/livfitt.app.com-1/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at gun0912.tedbottompicker.TedBottomPicker.startGalleryIntent(TedBottomPicker.java:536) 
        at gun0912.tedbottompicker.TedBottomPicker.access$200(TedBottomPicker.java:63) 
        at gun0912.tedbottompicker.TedBottomPicker$3.onItemClick(TedBottomPicker.java:282) 
        at gun0912.tedbottompicker.adapter.GalleryAdapter$1.onClick(GalleryAdapter.java:199) 
        at android.view.View.performClick(View.java:5215) 
        at android.view.View$PerformClick.run(View.java:21193) 
        at android.os.Handler.handleCallback(Handler.java:742) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:157) 
        at android.app.ActivityThread.main(ActivityThread.java:5571) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635) 
    	Suppressed: java.lang.ClassNotFoundException: com.gun0912.tedonactivityresult.TedOnActivityResult
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 14 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

I've been trying to get image using camera but the app crashes

**Comment by OmarAliSaid** [comment]
the same problem with me ..

**Comment by theGnartist** [comment]
@OmarAliSaid and @CodeDem try adding 
`implementation 'gun0912.ted:tedonactivityresult-rx1:1.0.6'` to your app gradle file.
This should resolve the class not found exception you are experiencing.

**Comment by rahul13agrawal** [comment]
@theGnartist Thank you so much for the resolution. It did help. The library is working fine now.

**Comment by theGnartist** [comment]
Awesome @rahul13agrawal, glad I could help.

**Comment by ParkSangGwon** [comment]
@CodeDem @OmarAliSaid @theGnartist @rahul13agrawal 
Sorry guys.
There are some maven library version error.
Now you don't need `implementation 'gun0912.ted:tedonactivityresult-rx1:1.0.6'`at v1.2.6.
Thanks your feedback and answer
