### ISSUE TITLE
Bottom Sheet doesn't open

### ISSUE THREAD

**Issue by jacobceles** [ParkSangGwon/TedBottomPicker#97]
I implemented the code below in my fragment. The activity enclosing the fragment is called only if and only if the permissions are given. I've used TedPermission for the same.

```
public class UploadFragment extends android.support.v4.app.Fragment{

    public UploadFragment() {
    }

    public static UploadFragment newInstance(String param) {
        return new UploadFragment();
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View v = inflater.inflate(R.layout.fragment_publish_troll_upload, container, false);

        TedBottomPicker tedBottomPicker = new TedBottomPicker.Builder(v.getContext())
                .setOnImageSelectedListener(new TedBottomPicker.OnImageSelectedListener() {
                    @Override
                    public void onImageSelected(Uri uri) {
                        Toast.makeText(getContext(), String.valueOf(uri), Toast.LENGTH_SHORT).show();
                    }
                })
                .create();

        tedBottomPicker.show(getFragmentManager());

        return v;
    }
}
```

But when I try to run the app it crashes when it reaches the fragment. I get the following error in my logcat:

```
07-22 18:53:23.585 1460-1460/com.abc.example E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.abc.example, PID: 1460
    java.lang.NoSuchMethodError: No virtual method load(Landroid/net/Uri;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/com.abc.example-SXzJJZFTJcn4lpOXa-2EbQ==/split_lib_dependencies_apk.apk)
        at gun0912.tedbottompicker.adapter.ImageGalleryAdapter.onBindViewHolder(ImageGalleryAdapter.java:112)
        at gun0912.tedbottompicker.adapter.ImageGalleryAdapter.onBindViewHolder(ImageGalleryAdapter.java:29)
        at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6735)
        at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6777)
        at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5706)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5973)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5812)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5808)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
        at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:557)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
        at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:171)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3878)
        at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3290)
        at android.view.View.measure(View.java:22254)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6611)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:22254)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6611)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:22254)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6611)
        at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:733)
        at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:805)
        at android.view.View.measure(View.java:22254)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6611)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:22254)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6611)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:22254)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6611)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:22254)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6611)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:22254)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6611)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:22254)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6611)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
07-22 18:53:23.586 1460-1460/com.abc.example E/AndroidRuntime:     at com.android.internal.policy.DecorView.onMeasure(DecorView.java:725)
        at android.view.View.measure(View.java:22254)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2593)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1668)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1925)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1556)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7327)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1039)
        at android.view.Choreographer.doCallbacks(Choreographer.java:851)
        at android.view.Choreographer.doFrame(Choreographer.java:742)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1025)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6753)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

The glide version I am using is 4.7.1 and the have both read and write permissions.

**Comment by jacobceles** [comment]
Fixed the issue by updating to version 1.2.6.
