### ISSUE TITLE
issue when take a picture using camera

### ISSUE THREAD

**Issue by HaroldYi** [ParkSangGwon/TedBottomPicker#99]
Test env. : LG G2 (Android v 5.x), Galaxy J7(2016, android 7.x)

we used this library for using camera.

but, our app is crashed when take a picture using camera.

we have 2 error.

````
1. Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Context.bindService(android.content.Intent, android.content.ServiceConnection, int)' on a null object reference
        at android.media.MediaScannerConnection.connect(MediaScannerConnection.java:119)
        at android.media.MediaScannerConnection.scanFile(MediaScannerConnection.java:238)
        at gun0912.tedbottompicker.TedBottomPicker.onActivityResultCamera(TedBottomPicker.java:581)
        at gun0912.tedbottompicker.TedBottomPicker.access$700(TedBottomPicker.java:63)
        at gun0912.tedbottompicker.TedBottomPicker$5.onActivityResult(TedBottomPicker.java:444)
        at com.gun0912.tedonactivityresult.ProxyActivity.onActivityResult(ProxyActivity.java:53)
        at android.app.Activity.dispatchActivityResult(Activity.java:6222)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:3570)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2962) 
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3007) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2373) 
        at android.app.ActivityThread.access$800(ActivityThread.java:149) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1284) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5292) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703) 
````

I also download your project and then I built and ran project at G2. 
but, your sample app and our app is crashed when take a picture using camera.

I tried to fix **TedBottomPicker.java**
and the built and ran sample project at LG G2 and the other phone.

as a result, your sample project worked very well.

I just add, change some of code.

> **_add_**
> line 74 : private static Context context;
> line 886 : TedBottomPicker.context = this.context;
> 
> _**change**_
> line 583 : getContext() -> this.context

If you agree pull request about this bug fix, I'll pull request. but, if you disagree,  please check this problem..

````
2.Caused by java.lang.NullPointerException: Attempt to read from field 'boolean gun0912.tedbottompicker.TedBottomPicker$Builder.showTitle' on a null object reference
       at gun0912.tedbottompicker.TedBottomPicker.setTitle(TedBottomPicker.java:555)
       at gun0912.tedbottompicker.TedBottomPicker.setupDialog(TedBottomPicker.java:172)
       at android.support.v4.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:331)
       at android.support.v4.app.Fragment.performGetLayoutInflater(Fragment.java:1226)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
       at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
       at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3200)
       at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:195)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:597)
       at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1256)
       at android.app.Activity.performStart(Activity.java:6973)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2937)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

````

I saw that #2 is solved version 1.2.0. but we used version 1.2.6. 

Thank you for providing this library. We use your libraries usefully.

**Comment by PR0GGRAM3D2WIN** [comment]
# OS Version: 9
# Device: Redmi Note 6 Pro
# RAM Free: 26.1%
# Disk Free: 61.5%
# TedBottomPicker Library Version: 2.0.1
--
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=27367, result=-1, data=null} to activity {com.softpal.gamya/com.gun0912.tedonactivityresult.ProxyActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Context.bindService(android.content.Intent, android.content.ServiceConnection, int)' on a null object reference
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4423)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4465)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6810)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Context.bindService(android.content.Intent, android.content.ServiceConnection, int)' on a null object reference
       at android.media.MediaScannerConnection.connect(MediaScannerConnection.java:119)
       at android.media.MediaScannerConnection.scanFile(MediaScannerConnection.java:243)
       at gun0912.tedbottompicker.TedBottomSheetDialogFragment.onActivityResultCamera(TedBottomSheetDialogFragment.java:550)
       at gun0912.tedbottompicker.TedBottomSheetDialogFragment.access$2000(TedBottomSheetDialogFragment.java:61)
       at gun0912.tedbottompicker.TedBottomSheetDialogFragment$5.onActivityResult(TedBottomSheetDialogFragment.java:413)
       at com.gun0912.tedonactivityresult.ProxyActivity.onActivityResult(ProxyActivity.java:53)
       at android.app.Activity.dispatchActivityResult(Activity.java:7590)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4416)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4465)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6810)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
